[package]
name = "cutefetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.2", features = ["derive"] }
colored = "2.0.0"
sysinfo = "0.28.4"
whoami = "1.4.0"
